# for project 1 you need only a for loop and an if statement
# and of course to use variables and math

# If we list all the natural numbers below 10 that are multiples of 3 or 5,
# we get 3, 5, 6 and 9. The sum of these multiples is 23.


"""
Euler #1
Find the sum of all the multiples of 3 or 5 below 1000.
"""

"""
Find the sum(all multiples of 3 or 5 (below 1000))
"""

n = 0
for




x = 0
for n in range(0, 1000):
    if ((n % 3) == 0) or ((n % 5) == 0):
        x = x + n
print (x)



"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""








n = 0
x = 1
y = 1
for z in range(0, 1000):
    z = x + y
    x = y
    y = z
    if (((z % 2) == 0) and (z < 4000000)):
        n = z + n
print (n)


n = 0
x = 1
y = 1
for z = x + y:
    x = y
    y = z
    if (((z % 2) == 0) and (z < 4000000)):
        n = z + n
print (n)

n = 0
x = 1
y = 1
for z = x + y:
    z < 4000000
    x = y
    y = z
if (((z % 2) == 0) and (z < 4000000)):
        n = z + n
print (n)
