# for project 1 you need only a for loop and an if statement
# and of course to use variables and math

# If we list all the natural numbers below 10 that are multiples of 3 or 5,
# we get 3, 5, 6 and 9. The sum of these multiples is 23.


"""
Euler #1
Find the sum of all the multiples of 3 or 5 below 1000.
"""

"""
Find the sum(all multiples of 3 or 5 (below 1000))
"""

n = 0
for




x = 0
for n in range(0, 1000):
    if ((n % 3) == 0) or ((n % 5) == 0):
        x = x + n
print (x)



"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""








n = 0
x = 1
y = 1
for z in range(0, 1000):
    z = x + y
    x = y
    y = z
    if (((z % 2) == 0) and (z < 4000000)):
        n = z + n
print (n)

"""""
better,cleaner
"""""

n = 0
x = 1
y = 1
while (y <= 4000000):
    z = x + y
    x = y
    y = z
    if (((z % 2) == 0) and (z <= 4000000)):
        n = z + n
print (n)



"""
problem 3

The prime factors of 13195 are 5, 7, 13 and 29.

What is the largest prime factor of the number 600851475143 ?

"""
def is_prime(x):




def ans(x):


for x in range(1, 13195):
    for y in range(1, x):
        ((x * y) == 600851475143) and not ((x % 2) == 0)
        if ((600851475143 % x) == 0) and ((600851475143) % y == 0):
                print(x, y)

x != y
(x * y) == 138717511
print (x, y)

138717511

x != y
for x in range(1, 13195):
    for y in range(x):
        ((x * y) == 600851475143)
        print (x)


""""
Problem 4
A palindromic number reads the same both ways. The largest palindrome made from the product of two 2-digit numbers is 9009 = 91 × 99.

Find the largest palindrome made from the product of two 3-digit numbers.
"""""




z = 0

for z in range(888, 1000):
    for x in range(888, z):
        znew = (x * z)
        z1 = str(znew)
        z1 = str(znew)
        z2 = list(z1)
        if (z2) == (z2[::-1]):
            print(max(z2))

while z = (101):
    if (z) = (z):
        print(z)

